name: GitHub CI/CD

on:
  push:
    branches:
      - main

jobs:
  # deploy-frontend:
  #     runs-on: ubuntu-latest
  #     steps:
  #         - name: Checkout code
  #           uses: actions/checkout@v2

  #         - name: Setup Docker
  #           uses: docker/setup-docker@v1

  #         - name: Login to Docker
  #           run: echo ${{ secrets.GC_KEY }} | docker login -u _json_key --password-stdin https://asia-northeast3-docker.pkg.dev

  #         - name: Build and deploy frontend
  #           run: |
  #               cd web
  #               ARTIFACT="asia-northeast3-docker.pkg.dev/industrial-balm-252203/dalgona"
  #               TAG="pipeline-test-2"
  #               echo "build dalgona-web:$TAG"
  #               docker build --build-arg VERSION="$TAG" . -t $ARTIFACT/dalgona-web:"$TAG"
  #               echo "push dalgona-web:$TAG"
  #               docker push $ARTIFACT/dalgona-web:"$TAG"
  #               echo "deploy dalgona-web:$TAG"
  #               gcloud run deploy dalgona-web --image $ARTIFACT/dalgona-web:"$TAG" --project=industrial-balm-252203 --region=asia-northeast3
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: move subDir
        run: cd fairy-tale-book
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        env:
          FOLDER: fairy-tale-book
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: leejaeyeop/ai-fairy-tale-book
          stage: main
          yaml: |
            name: fairytale-frontend
            app: web
            options:
              docbase: /dist
              nodeversion: "18"
              build: npm run production
              spa: true
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-docker@v1

      - name: Authenticate with gcloud
        run: |
          echo "${{ secrets.GC_KEY }}" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json

      - name: Login to Docker
        run: echo ${{ secrets.GC_KEY }} | docker login -u _json_key --password-stdin https://asia-northeast3-docker.pkg.dev < gcp-key.json

      - name: Build and deploy backend
        run: |
          cd servers
          ARTIFACT="asia-northeast3-docker.pkg.dev/fairytale-388005/fairytale"
          TAG="pipeline-test"
          echo "build api-server:$TAG"
          docker build --build-arg VERSION="$TAG" . -t $ARTIFACT/api-server:"$TAG"
          echo "push api-server:$TAG"
          docker push $ARTIFACT/api-server:"$TAG"
          echo "deploy api-server:$TAG"
          gcloud run deploy api-server --image $ARTIFACT/api-server:"$TAG" --project=fairytale-388005 --region=asia-northeast3 --execution-environment gen2 --allow-unauthenticated --service-account fs-identity
