name: GitHub CI/CD

on:
    push:
        branches:
            - main

jobs:
    deploy-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Docker
              uses: docker/setup-buildx-action@v1

            - name: create-json
              id: create-json
              uses: jsdaniell/create-json@1.1.2
              with:
                  name: "key.json"
                  json: ${{ secrets.GCP_KEY_JSON }}

            - name: Authenticate with gcloud
              run: |
                  gcloud auth activate-service-account deploy@fairytale-388005.iam.gserviceaccount.com --key-file=key.json
              env:
                  GC_KEY: ${{ secrets.GC_KEY }}
            - name: Login to Docker
              run: echo ${{ secrets.GC_KEY }} | docker login -u _json_key --password-stdin https://asia-northeast3-docker.pkg.dev < key.json

            - name: Generate Environment Variables File for Production
              run: |
                  cd api
                  echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
                  echo "STABILITY_API_KEY=$STABILITY_API_KEY" >> .env
                  echo "DEEPAI_API_KEY=$DEEPAI_API_KEY" >> .env

              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
                  DEEPAI_API_KEY: ${{ secrets.DEEPAI_API_KEY }}

            - name: Build and deploy backend
              run: |
                  cd api
                  ARTIFACT="asia-northeast3-docker.pkg.dev/fairytale-388005/fairytale"
                  TAG="$GITHUB_SHA"
                  echo "build api-server:$TAG"
                  docker build --build-arg VERSION="$TAG" . -t $ARTIFACT/api-server:"$TAG"
                  echo "push api-server:$TAG"
                  docker push $ARTIFACT/api-server:"$TAG"
                  echo "deploy api-server:$TAG"
                  gcloud run deploy api-server --image $ARTIFACT/api-server:"$TAG" --project=fairytale-388005 --region=asia-northeast3 --platform managed --allow-unauthenticated
